### ISSUE TITLE
 权限列表 通过关键字搜索未匹配相应结果

### ISSUE THREAD

**Issue by nondevops** [opendevops-cn/codo-admin#5]
当前版本:0.3
部署方式:虚拟机运行docker
问题描述: 
权限列表 通过关键字搜索未匹配相应结果
相关截图:
![image](https://user-images.githubusercontent.com/12181410/60876711-032f1e80-a26f-11e9-98ff-036f51ef64ae.png)

![image](https://user-images.githubusercontent.com/12181410/60876775-1fcb5680-a26f-11e9-9e2d-0f64b805afff.png)

**Comment by luciferYu** [comment]
这个权限系统怎么使用 如果自己二次开发API 有装饰器可以套用到接口吗？

**Comment by ss1917** [comment]
不需要，鉴权是通过网关来做的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opendevops-cn/codo-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月3日(星期三) 下午3:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [opendevops-cn/codo-admin]  权限列表 通过关键字搜索未匹配相应结果 (#5)





 
这个权限系统怎么使用 如果自己二次开发API 有装饰器可以套用到接口吗？
