### ISSUE TITLE
[需求]  通过api添加用户时应该把用户状态字段开放

### ISSUE THREAD

**Issue by nondevops** [opendevops-cn/codo-admin#6]
需求]  通过api添加用户时应该把用户状态字段开放
批量导入用户时发现用户状态默认为禁用,通过修改status=0临时修改初始化状态,后来想一想也觉得不靠谱.用户状态的字段 api接口应该开放出来,让用户自行选择是正常还是禁用.

**Comment by ss1917** [comment]
需求已经收录
